### ISSUE TITLE
Crash in "Shape Source from Icon" in example app

### ISSUE THREAD

**Issue by alexiri** [react-native-mapbox/maps#48]
**Describe the bug**
The app crashes with the following stacktrace when running the "Shape Source from Icon" example:

```
05-18 19:19:12.176  1174  1174 E AndroidRuntime: FATAL EXCEPTION: main
05-18 19:19:12.176  1174  1174 E AndroidRuntime: Process: com.rnmapboxglexample, PID: 1174
05-18 19:19:12.176  1174  1174 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.Style.addImage(java.lang.String, android.graphics.Bitmap)' on a null object reference
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.mapbox.rctmgl.components.styles.sources.RCTMGLShapeSource.addToMap(RCTMGLShapeSource.java:59)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onMapReady(RCTMGLMapView.java:373)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1154)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1140)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:207)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:61)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:321)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-18 19:19:12.176  1174  1174 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Versions:**
 - Platfrom: Android
 - Device: Oneplus 3T
 - OS: 8.0.0
 - SDK Version: 28
 - React Native Version: 0.59.0

**Comment by alexiri** [comment]
Fixed in #51.
